load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "connect.go",
        "graphd.go",
        "log.go",
        "url.go",
    ],
    importpath = "github.com/google/graphd/go/graphd/go/graphd",
    visibility = ["//visibility:public"],
)
