# Description:
#   libcm - a memory allocation framework.

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "libcm",
    srcs = [
        "cm-argv.c",
        "cm-buffer.c",
        "cm-build-version.c",
        "cm-c.c",
        "cm-error.c",
        "cm-hash.c",
        "cm-heap.c",
        "cm-list.c",
        "cm-malcpy.c",
        "cm-prefix.c",
        "cm-resource.c",
        "cm-runtime-statistics.c",
        "cm-sprintf.c",
        "cm-substr.c",
        "cm-trace.c",
        "cm-zalloc.c",
    ],
    hdrs = ["cm.h"],
    copts = ["-g"],
)
